sudo: required
services:
  - docker

env: 
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISBALE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_fb10a834873f_key -iv $encrypted_fb10a834873f_iv -in serv-acc.json.enc -out serv-acc.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source  $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file serv-acc.json
  - gcloud config set project <google-project-name>
  - gcloud config set compute/zone <cluster-location>
  - gcloud container clusters get-credentials <cluster-name>

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mumajid/reactapp-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mumajid/reactapp-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master