sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_fb10a834873f_key -iv $encrypted_fb10a834873f_iv -in serv-acc.json.enc -out serv-acc.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source  $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json