language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mumajid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mumajid/docker-react npm run test