sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mumajid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mumajid/react-test npm test

after_success:
  # Build production images
  - docker build -t mumajid/multi-client ./client
  - docker build -t mumajid/multi-nginx ./nginx
  - docker build -t mumajid/multi-server ./server
  - docker build -t mumajid/multi-worker ./worker
  # Log in to the docker CLI (PASSWORD is inserted on the travis project dashboard as env)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mumajid/multi-client
  - docker push mumajid/multi-nginx
  - docker push mumajid/multi-server
  - docker push mumajid/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY